### ISSUE TITLE
high temperature when plug in xbox wireless adapter.

### ISSUE THREAD

**Issue by fmowl10** [medusalix/xow#189] opened 2021-11-01 03:11 UTC
this is my desktop enviroment

> CPU : AMD Ryzen 7 5800x
RAM : 32 GB
OS : Linux (5.13.0-21-generic)
Distribution : Ubuntu 21.10
cabextract version 1.9
libusb 1.0.24-3 
systemd 248.3

![스크린샷, 2021-11-01 11-39-37](https://user-images.githubusercontent.com/6753999/139615740-ea0eec50-64a4-4b6f-aca9-11af1aeff7e8.png)

like image when plug in wireless adapter, cpu temperature keep 60℃.

**Comment by kakra** [comment] 2021-11-01 08:20
Is this another instance of #181?

**Comment by Soltra45** [comment] 2021-12-28 15:34
Same issue here with the same processor. It seems like it is an instance of #181 or #141 as @kakra mentioned.

**Comment by medusalix** [comment] 2022-03-20 22:15
Duplicate of #141.

**Closed by medusalix** 2022-03-20 22:15 UTC
Labels: invalid/duplicate
