### ISSUE TITLE
Elite Wireless Support (1698)

### ISSUE THREAD

**Issue by rwilliams** [medusalix/xow#12] opened 2019-12-25 01:34 UTC
I have the Original Elite Wireless and I'd be more than happy to test.

**Comment by PopeRigby** [comment] 2019-12-25 01:52
Why did you close this?

**Comment by rwilliams** [comment] 2019-12-25 01:54
It seems like it's already a pretty well known limitation after looking at the other threads. I'll re-open though.

**Comment by PopeRigby** [comment] 2019-12-25 01:54
Yeah. You should leave it open so we can track the issue.

**Comment by Hielyr** [comment] 2019-12-27 12:03
> Yeah. You should leave it open so we can track the issue.

Right. It's a feature request, not a bug.

**Comment by rwilliams** [comment] 2020-01-13 17:08
I'd be more than happy to do a packet capture for this with Wireshark if that would be helpful though I'll probably need a bit of guidance on getting the proper data.

**Comment by medusalix** [comment] 2020-01-13 20:10
Yes, that would definitely be helpful. What happens when you try to connect/pair your controller using xow on Linux?

**Comment by rwilliams** [comment] 2020-01-13 20:22
> xow on  master 
➜ sudo ./xow
2020-01-13 12:20:50 INFO  - xow v0.2-5-gcbe6761 ©Severin v. W.
2020-01-13 12:20:50 INFO  - Dongle plugged in
2020-01-13 12:20:50 INFO  - Chip address: 62:45:b5:0b:84:bb
2020-01-13 12:20:50 INFO  - Dongle initialized
2020-01-13 12:21:07 INFO  - Pairing initiated
2020-01-13 12:21:07 INFO  - Pairing initiated
2020-01-13 12:21:08 INFO  - Pairing initiated
2020-01-13 12:21:08 INFO  - Pairing initiated
2020-01-13 12:21:29 INFO  - Pairing initiated
2020-01-13 12:21:29 INFO  - Pairing initiated
2020-01-13 12:21:29 INFO  - Pairing initiated
2020-01-13 12:21:29 INFO  - Pairing initiated

I hit paring twice here. I'm a little behind on the build but i don't think you've added any related changes since.

**Comment by rwilliams** [comment] 2020-01-13 20:27
I just updated to master for science, same results.

**Comment by rwilliams** [comment] 2020-01-13 20:40
For Wireshark do I just select all the USBPcap options and go through a pairing cycle?

**Comment by medusalix** [comment] 2020-01-13 20:50
Yes, first you have to find the correct USBPcap device. If you plug in the dongle and you see lots of messages appearing, then it's probably the correct one. Then you pair your controller, generate some inputs (buttons, triggers, bumpers) and disconnect the controller.

**Comment by rwilliams** [comment] 2020-01-13 22:42
Ok. I think i got the filters right to only capture the receiver and controller. The first capture is turning the controller on, already paired. Doing a pairing cycle and then hitting a bunch of buttons. The second capture is specifically for the paddles on the underside. Starting with Top right(B)
, Bottom right(B), Top left(X), Bottom Left(X). `I only actually use one paddle on each side for rocket league so that's why the bindings are the same.` I've attached the config from xbox accessories app. I'm more than happy to redo this with different bindings if needed.

[elitewireless1.pcapng.gz](https://github.com/medusalix/xow/files/4056238/elitewireless1.pcapng.gz)
[paddles.pcapng.gz](https://github.com/medusalix/xow/files/4056240/paddles.pcapng.gz)
![bindings](https://user-images.githubusercontent.com/29144/72298108-34b7e680-3612-11ea-9dfe-945e96bae552.jpg)

**Comment by medusalix** [comment] 2020-01-14 16:59
I've looked through your captures and didn't spot any obvious differences that might prevent it from pairing. Could you do another capture on Linux please (with xow open)? The debug logs might also be helpful (`make` with `BUILD=DEBUG`). Please make sure to wait for around 20 seconds after you press the pairing button (the pairing can be quite slow).

**Comment by rwilliams** [comment] 2020-01-14 17:10
Will do

**Comment by rwilliams** [comment] 2020-01-14 17:52
https://wiki.wireshark.org/CaptureSetup/USB#Linux

I have no idea what to choose here to filter.
![Screenshot from 2020-01-14 09-50-47](https://user-images.githubusercontent.com/29144/72368681-68971880-36b3-11ea-88d3-694c98548395.png)

I think when I chose any it was getting data from the dongle but i'd like to get a capture that's more specific. Where are the logs for xow located?

**Comment by medusalix** [comment] 2020-01-14 19:27
You have to run `sudo modprobe usbmon` for USB devices to appear in Wireshark.

**Comment by rwilliams** [comment] 2020-01-14 19:28
Thanks! Will post soon.

**Comment by rwilliams** [comment] 2020-01-15 12:30
```
xow on  master took 31s 
➜ sudo ./xow
2020-01-15 04:18:56 INFO  - xow v0.2-21-g6de45b3 ©Severin v. W.
2020-01-15 04:18:57 INFO  - Dongle plugged in
2020-01-15 04:18:57 INFO  - Chip address: 62:45:b5:0b:84:bb
2020-01-15 04:18:57 INFO  - Dongle initialized
2020-01-15 04:19:02 INFO  - Pairing initiated
2020-01-15 04:19:02 INFO  - Pairing initiated
2020-01-15 04:19:02 INFO  - Pairing initiated
2020-01-15 04:19:02 INFO  - Pairing initiated
2020-01-15 04:19:21 INFO  - Controller '1' connected
2020-01-15 04:19:21 INFO  - Controller '1' disconnected
2020-01-15 04:19:42 INFO  - Controller '1' connected
2020-01-15 04:22:44 ERROR - Error in bulk read: 1
2020-01-15 04:22:44 ERROR - Error in bulk read: 1
2020-01-15 04:22:44 INFO  - Dongle removed
^C

xow on  master took 3m 52s 
➜ sudo ./xow
2020-01-15 04:23:01 INFO  - xow v0.2-21-g6de45b3 ©Severin v. W.
2020-01-15 04:23:01 INFO  - Dongle plugged in
2020-01-15 04:23:01 INFO  - Chip address: 62:45:b5:0b:84:bb
2020-01-15 04:23:01 INFO  - Dongle initialized
2020-01-15 04:23:01 INFO  - Controller '1' connected
```

Well it looks like it pairs. It shows up properly in steam. None of the inputs seem to work though. I got usbmon going but i didn't see any action on any of the usbmon filters that seemed like they were from the dongle when I looked at them.

**Comment by medusalix** [comment] 2020-01-15 20:49
Looks like the pairing works just fine (sometimes it takes a while for controllers to connect, even on Windows). The input doesn't work because the packet the elite controllers sends is a little bit bigger than the normal input (due to the additional paddles) and xow ignores packets with an incorrect size. That shouldn't be too hard to fix though...

**Comment by medusalix** [comment] 2020-01-17 10:16
@rwilliams What inputs do the paddles generate when you plug in the controller over USB? If you run `evtest` you should be able to see all the events generated.

**Comment by rwilliams** [comment] 2020-01-17 13:11
This is what I expected. There is no difference between hitting b or a paddle mapped to b. I tested for x too. Can test more bind combinations to look for edge cases if you need. In this case my b and x were east and north respectively.

> Supported events:
>   Event type 0 (EV_SYN)
>   Event type 1 (EV_KEY)
>     Event code 304 (BTN_SOUTH)
>     Event code 305 (BTN_EAST)
>     Event code 307 (BTN_NORTH)
>     Event code 308 (BTN_WEST)
>     Event code 310 (BTN_TL)
>     Event code 311 (BTN_TR)
>     Event code 314 (BTN_SELECT)
>     Event code 315 (BTN_START)
>     Event code 316 (BTN_MODE)
>     Event code 317 (BTN_THUMBL)
>     Event code 318 (BTN_THUMBR)
>   Event type 3 (EV_ABS)
>     Event code 0 (ABS_X)
>       Value     93
>       Min   -32768
>       Max    32767
>       Fuzz      16
>       Flat     128
>     Event code 1 (ABS_Y)
>       Value   -208
>       Min   -32768
>       Max    32767
>       Fuzz      16
>       Flat     128
>     Event code 2 (ABS_Z)
>       Value      0
>       Min        0
>       Max     1023
>     Event code 3 (ABS_RX)
>       Value    637
>       Min   -32768
>       Max    32767
>       Fuzz      16
>       Flat     128
>     Event code 4 (ABS_RY)
>       Value   -192
>       Min   -32768
>       Max    32767
>       Fuzz      16
>       Flat     128
>     Event code 5 (ABS_RZ)
>       Value      0
>       Min        0
>       Max     1023
>     Event code 16 (ABS_HAT0X)
>       Value      0
>       Min       -1
>       Max        1
>     Event code 17 (ABS_HAT0Y)
>       Value      0
>       Min       -1
>       Max        1
>   Event type 21 (EV_FF)
>     Event code 80 (FF_RUMBLE)
>     Event code 81 (FF_PERIODIC)
>     Event code 88 (FF_SQUARE)
>     Event code 89 (FF_TRIANGLE)
>     Event code 90 (FF_SINE)
>     Event code 96 (FF_GAIN)
> Properties:
> Testing ... (interrupt to exit)
> Event: time 1579266373.053129, type 3 (EV_ABS), code 1 (ABS_Y), value -140
> Event: time 1579266373.053129, -------------- SYN_REPORT ------------
> Event: time 1579266373.381130, type 3 (EV_ABS), code 4 (ABS_RY), value -125
> Event: time 1579266373.381130, -------------- SYN_REPORT ------------
> Event: time 1579266374.949144, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266374.949144, -------------- SYN_REPORT ------------
> Event: time 1579266375.029144, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266375.029144, -------------- SYN_REPORT ------------
> Event: time 1579266376.857161, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266376.857161, -------------- SYN_REPORT ------------
> Event: time 1579266377.005160, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266377.005160, -------------- SYN_REPORT ------------
> Event: time 1579266378.297178, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266378.297178, -------------- SYN_REPORT ------------
> Event: time 1579266378.401175, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266378.401175, -------------- SYN_REPORT ------------
> Event: time 1579266380.261192, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266380.261192, -------------- SYN_REPORT ------------
> Event: time 1579266380.385193, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266380.385193, -------------- SYN_REPORT ------------
> Event: time 1579266382.253210, type 3 (EV_ABS), code 1 (ABS_Y), value -51
> Event: time 1579266382.253210, -------------- SYN_REPORT ------------
> Event: time 1579266382.261209, type 3 (EV_ABS), code 1 (ABS_Y), value 18
> Event: time 1579266382.261209, -------------- SYN_REPORT ------------
> Event: time 1579266382.269209, type 3 (EV_ABS), code 1 (ABS_Y), value 99
> Event: time 1579266382.269209, -------------- SYN_REPORT ------------
> Event: time 1579266382.277208, type 3 (EV_ABS), code 1 (ABS_Y), value 190
> Event: time 1579266382.277208, -------------- SYN_REPORT ------------
> Event: time 1579266382.285209, type 3 (EV_ABS), code 1 (ABS_Y), value 283
> Event: time 1579266382.285209, -------------- SYN_REPORT ------------
> Event: time 1579266382.293209, type 3 (EV_ABS), code 1 (ABS_Y), value 376
> Event: time 1579266382.293209, -------------- SYN_REPORT ------------
> Event: time 1579266382.301208, type 3 (EV_ABS), code 1 (ABS_Y), value 451
> Event: time 1579266382.301208, -------------- SYN_REPORT ------------
> Event: time 1579266382.317209, type 3 (EV_ABS), code 1 (ABS_Y), value 559
> Event: time 1579266382.317209, -------------- SYN_REPORT ------------
> Event: time 1579266382.333210, type 3 (EV_ABS), code 1 (ABS_Y), value 627
> Event: time 1579266382.333210, -------------- SYN_REPORT ------------
> Event: time 1579266382.365210, type 3 (EV_ABS), code 1 (ABS_Y), value 700
> Event: time 1579266382.365210, -------------- SYN_REPORT ------------
> Event: time 1579266382.505211, type 3 (EV_ABS), code 1 (ABS_Y), value 591
> Event: time 1579266382.505211, -------------- SYN_REPORT ------------
> Event: time 1579266384.277228, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266384.277228, -------------- SYN_REPORT ------------
> Event: time 1579266384.449229, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266384.449229, -------------- SYN_REPORT ------------
> Event: time 1579266385.481238, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266385.481238, -------------- SYN_REPORT ------------
> Event: time 1579266385.633240, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266385.633240, -------------- SYN_REPORT ------------
> Event: time 1579266386.713249, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266386.713249, -------------- SYN_REPORT ------------
> Event: time 1579266386.829250, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266386.829250, -------------- SYN_REPORT ------------
> Event: time 1579266387.545257, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266387.545257, -------------- SYN_REPORT ------------
> Event: time 1579266387.705258, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266387.705258, -------------- SYN_REPORT ------------
> Event: time 1579266389.073275, type 1 (EV_KEY), code 308 (BTN_WEST), value 1
> Event: time 1579266389.073275, -------------- SYN_REPORT ------------
> Event: time 1579266389.177271, type 1 (EV_KEY), code 308 (BTN_WEST), value 0
> Event: time 1579266389.177271, -------------- SYN_REPORT ------------
> Event: time 1579266389.753276, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 1
> Event: time 1579266389.753276, -------------- SYN_REPORT ------------
> Event: time 1579266389.901277, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 0
> Event: time 1579266389.901277, -------------- SYN_REPORT ------------
> Event: time 1579266394.873324, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266394.873324, -------------- SYN_REPORT ------------
> Event: time 1579266394.973322, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266394.973322, -------------- SYN_REPORT ------------
> Event: time 1579266395.509328, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266395.509328, -------------- SYN_REPORT ------------
> Event: time 1579266395.693329, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266395.693329, -------------- SYN_REPORT ------------
> Event: time 1579266396.213334, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266396.213334, -------------- SYN_REPORT ------------
> Event: time 1579266396.361335, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266396.361335, -------------- SYN_REPORT ------------
> Event: time 1579266396.913340, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266396.913340, -------------- SYN_REPORT ------------
> Event: time 1579266397.069340, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266397.069340, -------------- SYN_REPORT ------------
> Event: time 1579266398.009350, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266398.009350, -------------- SYN_REPORT ------------
> Event: time 1579266398.213351, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266398.213351, -------------- SYN_REPORT ------------
> Event: time 1579266398.645355, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266398.645355, -------------- SYN_REPORT ------------
> Event: time 1579266398.849357, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266398.849357, -------------- SYN_REPORT ------------
> Event: time 1579266399.293361, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266399.293361, -------------- SYN_REPORT ------------
> Event: time 1579266399.425361, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266399.425361, -------------- SYN_REPORT ------------
> Event: time 1579266399.921366, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266399.921366, -------------- SYN_REPORT ------------
> Event: time 1579266400.049367, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266400.049367, -------------- SYN_REPORT ------------
> Event: time 1579266400.593375, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266400.593375, -------------- SYN_REPORT ------------
> Event: time 1579266400.741373, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266400.741373, -------------- SYN_REPORT ------------
> Event: time 1579266401.237377, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266401.237377, -------------- SYN_REPORT ------------
> Event: time 1579266401.341379, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266401.341379, -------------- SYN_REPORT ------------
> Event: time 1579266401.725382, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266401.725382, -------------- SYN_REPORT ------------
> Event: time 1579266401.837382, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266401.837382, -------------- SYN_REPORT ------------
> Event: time 1579266402.173386, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266402.173386, -------------- SYN_REPORT ------------
> Event: time 1579266402.309386, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266402.309386, -------------- SYN_REPORT ------------
> Event: time 1579266402.537389, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266402.537389, -------------- SYN_REPORT ------------
> Event: time 1579266402.661390, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266402.661390, -------------- SYN_REPORT ------------
> Event: time 1579266402.885392, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
> Event: time 1579266402.885392, -------------- SYN_REPORT ------------
> Event: time 1579266403.033393, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
> Event: time 1579266403.033393, -------------- SYN_REPORT ------------
> Event: time 1579266403.861401, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266403.861401, -------------- SYN_REPORT ------------
> Event: time 1579266403.993402, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266403.993402, -------------- SYN_REPORT ------------
> Event: time 1579266404.473420, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266404.473420, -------------- SYN_REPORT ------------
> Event: time 1579266404.537421, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266404.537421, -------------- SYN_REPORT ------------
> Event: time 1579266404.957424, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
> Event: time 1579266404.957424, -------------- SYN_REPORT ------------
> Event: time 1579266405.145426, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
> Event: time 1579266405.145426, -------------- SYN_REPORT ------------
> Event: time 1579266406.861441, type 3 (EV_ABS), code 1 (ABS_Y), value 494
> Event: time 1579266406.861441, -------------- SYN_REPORT ------------
> Event: time 1579266407.161444, type 3 (EV_ABS), code 4 (ABS_RY), value 125
> Event: time 1579266407.161444, -------------- SYN_REPORT ------------
> Event: time 1579266407.169444, type 3 (EV_ABS), code 4 (ABS_RY), value -8
> Event: time 1579266407.169444, -------------- SYN_REPORT ------------
> Event: time 1579266407.177444, type 3 (EV_ABS), code 1 (ABS_Y), value 382
> Event: time 1579266407.177444, -------------- SYN_REPORT ------------
> Event: time 1579266407.185444, type 3 (EV_ABS), code 1 (ABS_Y), value 146
> Event: time 1579266407.185444, type 3 (EV_ABS), code 4 (ABS_RY), value -207
> Event: time 1579266407.185444, -------------- SYN_REPORT ------------
> Event: time 1579266407.193444, type 3 (EV_ABS), code 1 (ABS_Y), value -12
> Event: time 1579266407.193444, -------------- SYN_REPORT ------------
> Event: time 1579266407.201444, type 3 (EV_ABS), code 1 (ABS_Y), value -119
> Event: time 1579266407.201444, type 3 (EV_ABS), code 4 (ABS_RY), value -307
> Event: time 1579266407.201444, -------------- SYN_REPORT ------------
> Event: time 1579266407.217444, type 3 (EV_ABS), code 1 (ABS_Y), value -219
> Event: time 1579266407.217444, -------------- SYN_REPORT ------------
> Event: time 1579266407.225444, type 3 (EV_ABS), code 4 (ABS_RY), value -407
> Event: time 1579266407.225444, -------------- SYN_REPORT ------------
> Event: time 1579266407.241444, type 3 (EV_ABS), code 1 (ABS_Y), value -332
> Event: time 1579266407.241444, -------------- SYN_REPORT ------------
> Event: time 1579266407.309445, type 3 (EV_ABS), code 1 (ABS_Y), value -429
> Event: time 1579266407.309445, -------------- SYN_REPORT ------------
> Event: time 1579266407.477447, type 3 (EV_ABS), code 3 (ABS_RX), value 886
> Event: time 1579266407.477447, type 3 (EV_ABS), code 4 (ABS_RY), value -506
> Event: time 1579266407.477447, -------------- SYN_REPORT ------------
> Event: time 1579266407.485433, type 3 (EV_ABS), code 1 (ABS_Y), value -314
> Event: time 1579266407.485433, type 3 (EV_ABS), code 3 (ABS_RX), value 1069
> Event: time 1579266407.485433, type 3 (EV_ABS), code 4 (ABS_RY), value -309
> Event: time 1579266407.485433, -------------- SYN_REPORT ------------
> Event: time 1579266407.493446, type 3 (EV_ABS), code 1 (ABS_Y), value -204
> Event: time 1579266407.493446, type 3 (EV_ABS), code 3 (ABS_RX), value 1202
> Event: time 1579266407.493446, -------------- SYN_REPORT ------------
> Event: time 1579266407.501446, type 3 (EV_ABS), code 3 (ABS_RX), value 1310
> Event: time 1579266407.501446, -------------- SYN_REPORT ------------
> Event: time 1579266407.509447, type 3 (EV_ABS), code 1 (ABS_Y), value -117
> Event: time 1579266407.509447, -------------- SYN_REPORT ------------
> Event: time 1579266407.517446, type 3 (EV_ABS), code 3 (ABS_RX), value 1452
> Event: time 1579266407.517446, -------------- SYN_REPORT ------------
> Event: time 1579266407.537447, type 3 (EV_ABS), code 1 (ABS_Y), value -42
> Event: time 1579266407.537447, type 3 (EV_ABS), code 3 (ABS_RX), value 1556
> Event: time 1579266407.537447, type 3 (EV_ABS), code 4 (ABS_RY), value -242
> Event: time 1579266407.537447, -------------- SYN_REPORT ------------
> Event: time 1579266407.561447, type 3 (EV_ABS), code 3 (ABS_RX), value 1657
> Event: time 1579266407.561447, -------------- SYN_REPORT ------------
> Event: time 1579266407.601447, type 3 (EV_ABS), code 1 (ABS_Y), value 24
> Event: time 1579266407.601447, -------------- SYN_REPORT ------------
> Event: time 1579266407.917450, type 3 (EV_ABS), code 3 (ABS_RX), value 1749
> Event: time 1579266407.917450, -------------- SYN_REPORT ------------
> Event: time 1579266408.225439, type 3 (EV_ABS), code 4 (ABS_RY), value -175
> Event: time 1579266408.225439, -------------- SYN_REPORT ------------
> Event: time 1579266410.461458, type 3 (EV_ABS), code 0 (ABS_X), value 30
> Event: time 1579266410.461458, -------------- SYN_REPORT ------------

**Comment by medusalix** [comment] 2020-01-17 20:34
> There is no difference between hitting b or a paddle mapped to b.

That looks like Microsoft actually implemented the button remapping in hardware. Based on your paddle captures it seems like we can just treat the bigger input packets as those of a normal Xbox One controller in the code. Please checkout the [`elite`](https://github.com/medusalix/xow/tree/elite) and let me know if it works 😃.

**Comment by rwilliams** [comment] 2020-01-17 20:35
Will do. Yeah sorry for not mentioning earlier that's it's all handled via firmware/hardware internally. I have to map the buttons in Windows but the mappings work without software support just fine in linux.

**Comment by rwilliams** [comment] 2020-01-17 21:05
Looks good. Pairing still takes some effort though. Maybe the elite wireless 2 will just work now.

**Comment by medusalix** [comment] 2020-01-17 21:13
Yeah, both elite controller models should work now. Have you got an elite v2 that you can test this with?

**Comment by rwilliams** [comment] 2020-01-17 21:14
I don't unfortunately. I've been pretty happy with my original elite so it's hard to justify dropping the money on the updated one.

**Comment by medusalix** [comment] 2020-01-17 21:29
Yes, it's **very** expensive and the built-in battery would be a dealbreaker for me. I've merged the changes into master in b58edb4ce50910fb7401c3d31919b2cc448aaaba, so I'll close this now.

**Closed by medusalix** 2020-01-17 21:29 UTC
Labels: compatibility, enhancement

**Comment by Hielyr** [comment] 2020-01-31 16:26
I have a v2 I can test with if necessary. I'll work on seeing if it works with the default build with the v1 changes added, and if not we can go from there.

**Comment by Hielyr** [comment] 2020-02-01 18:42
> I have a v2 I can test with if necessary. I'll work on seeing if it works with the default build with the v1 changes added, and if not we can go from there.

I have confirmed that the v2 Elite controller works as well! 
The model of the controller I'm using is 1797.

**Comment by rwilliams** [comment] 2020-02-01 19:03
Off topic but if I can resell or gift my V1 is the V2 worth getting?

**Comment by Hielyr** [comment] 2020-02-01 21:23
> Off topic but if I can resell or gift my V1 is the V2 worth getting?

I've never owned a v1, so I'm unable to make a direct comparison. 
What convinced me to get one for myself was this video review by Tim Rogers: https://www.youtube.com/watch?v=PhrNA07kzjc

He goes into a pretty decent comparison between the the two controllers.
