### ISSUE TITLE
Uses 100% one CPU thread

### ISSUE THREAD

**Issue by zaryuta** [medusalix/xow#181] opened 2021-08-22 08:10 UTC
Uses 100% of one CPU thread. Tried on Manjaro kernel 5.13 and PopOs kernel 5.12.

**Comment by Galcian79** [comment] 2021-09-06 15:34
I patched libusb from source, i confirm now it works as intended.

**Comment by sorgelig** [comment] 2021-09-10 19:58
@Galcian79 
which patch you've used and to which libusb version?

**Comment by Galcian79** [comment] 2021-09-10 20:57
> @Galcian79
> which patch you've used and to which libusb version?

The version i patched is the latest 1.0.24
This is the upstreamed patch https://github.com/libusb/libusb/commit/32a22069428cda9d63aa666e92fb8882a83d4515

**Comment by sorgelig** [comment] 2021-09-11 15:40
i see.. 
i think it's better to compile statically with older libusb and leave current libusb version in system for stability purpose. At least till 1.0.25 release.

**Comment by medusalix** [comment] 2022-03-20 22:16
Duplicate of #141.

**Closed by medusalix** 2022-03-20 22:16 UTC
Labels: invalid/duplicate
